# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

class TestLandingPage:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_landingpage(self):
        # Step 1: Open the website
        self.driver.get("http://localhost:5173/")
        # Step 2: Set the window size
        self.driver.set_window_size(1552, 832)
        # Step 3: Click the navigation icon
        self.driver.find_element(By.ID, "nav-icon").click()
        # Step 4: Click the collections link
        self.driver.find_element(By.CSS_SELECTOR, ".nav-text:nth-child(2) > .collections").click()

        # Step 5: Mouse over the collections link
        element = self.driver.find_element(By.CSS_SELECTOR, ".nav-text:nth-child(2) > .collections")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()

       

        

       
