# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestContinueshopping1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_continueshopping1(self):
    # Test name: continueshopping1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:5173/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | id=nav-icon | 
    self.driver.find_element(By.ID, "nav-icon").click()
    # 4 | click | linkText=CART | 
    self.driver.find_element(By.LINK_TEXT, "CART").click()
    # 5 | click | linkText=Continue Shopping | 
    self.driver.find_element(By.LINK_TEXT, "Continue Shopping").click()
  
