# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestShowcart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_showcart(self):
    # Test name: showcart
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:5173/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | css=.nav-text:nth-child(2) > .collections | 
    self.driver.find_element(By.CSS_SELECTOR, ".nav-text:nth-child(2) > .collections").click()
    # 4 | click | css=.svg-icon | 
    self.driver.find_element(By.CSS_SELECTOR, ".svg-icon").click()
    # 5 | mouseOver | css=.svg-icon | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".svg-icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    
  
