# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignup():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_signup(self):
        # Step 1: Open the website
        self.driver.get("http://localhost:5173/")
        # Step 2: Set the window size
        self.driver.set_window_size(1552, 832)
        # Step 3: Click the navigation icon
        self.driver.find_element(By.ID, "nav-icon").click()
        # Step 4: Click the LOGIN link
        self.driver.find_element(By.LINK_TEXT, "LOGIN").click()
        # Step 5: Click the Signup link
        self.driver.find_element(By.LINK_TEXT, "Signup").click()
        # Step 6: Click the username field and type the username
        self.driver.find_element(By.ID, "uname").click()
        self.driver.find_element(By.ID, "uname").send_keys("KY123")
        # Step 7: Click outside to trigger form validation (if necessary)
        self.driver.find_element(By.CSS_SELECTOR, "form").click()
        # Step 8: Click the email field and type the email
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("krishna123@gmail.com")
        # Step 9: Click the password field and type the password
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("KY123")
        # Step 10: Click the confirm password field and type the password again
        self.driver.find_element(By.ID, "confirm-password").click()
        self.driver.find_element(By.ID, "confirm-password").send_keys("KY123")
        # Step 11: Click the submit button
        self.driver.find_element(By.CSS_SELECTOR, ".button").click()

        # Step 12: Handle incorrect password scenario by retyping passwords
        # This step seems redundant but let's keep it if it's intentional
        self.driver.find_element(By.ID, "password").clear()
        self.driver.find_element(By.ID, "password").send_keys("KY1a23")
        self.driver.find_element(By.ID, "confirm-password").clear()
        self.driver.find_element(By.ID, "confirm-password").send_keys("KY1a23")
        self.driver.find_element(By.CSS_SELECTOR, ".button").click()

        # Step 13: Handle incorrect username scenario
        self.driver.find_element(By.ID, "uname").clear()
        self.driver.find_element(By.ID, "uname").send_keys("KY")
        self.driver.find_element(By.CSS_SELECTOR, ".button").click()
