# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

class TestWatchDetails:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_watchdetails(self):
        # Step 1: Open the website
        self.driver.get("http://localhost:5173/")
        # Step 2: Set the window size
        self.driver.set_window_size(1552, 832)
        # Step 3: Click on the collections link
        self.driver.find_element(By.CSS_SELECTOR, ".nav-text:nth-child(2) > .collections").click()

        # Step 4: Optional mouse over on the collections link (if needed)
        collections_element = self.driver.find_element(By.CSS_SELECTOR, ".nav-text:nth-child(2) > .collections")
        actions = ActionChains(self.driver)
        actions.move_to_element(collections_element).perform()

        # Step 5: Move the mouse away (optional)
        actions.move_by_offset(0, 0).perform()

        # Step 6: Click on the first item in the list
        self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(1) .h-128").click()
